laravel/app/routes.php
<?php

// Front-end

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('perfil', ['as' => 'perfil', 'uses' => 'PerfilController@index']);
Route::get('projetos', ['as' => 'projetos', 'uses' => 'ProjetosController@index']);
Route::get('mostras', ['as' => 'mostras', 'uses' => 'MostrasController@index']);
Route::get('imprensa', ['as' => 'imprensa', 'uses' => 'ImprensaController@index']);
Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);


// Painel

Route::get('painel', [
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
]);

Route::get('painel/login', [
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
]);
Route::post('painel/login', [
    'as'   => 'painel.auth',
    'uses' => 'Painel\HomeController@attempt'
]);
Route::get('painel/logout', [
    'as'   => 'painel.logout',
    'uses' => 'Painel\HomeController@logout'
]);

Route::group(['prefix' => 'painel', 'before' => 'auth'], function() {
    Route::resource('banners', 'Painel\BannersController');

    Route::resource('perfil', 'Painel\PerfilController');

    Route::resource('projetos', 'Painel\ProjetosController');
    Route::resource('projetos.imagens', 'Painel\ProjetosImagensController');

    Route::resource('mostras', 'Painel\MostrasController');
    Route::resource('mostras.imagens', 'Painel\MostrasImagensController');

    Route::get('imprensa/delete-image/{imprensa_id}', [
        'as'   => 'painel.imprensa.deleteImage',
        'uses' => 'Painel\ImprensaController@deleteImage'
    ]);
    Route::get('imprensa/delete-pdf/{imprensa_id}', [
        'as'   => 'painel.imprensa.deletePdf',
        'uses' => 'Painel\ImprensaController@deletePdf'
    ]);
    Route::resource('imprensa', 'Painel\ImprensaController');
    Route::resource('imprensa.imagens', 'Painel\ImprensaImagensController');

    Route::resource('contato/recebidos', 'Painel\ContatosRecebidosController');
    Route::resource('contato', 'Painel\ContatoController');

    Route::resource('usuarios', 'Painel\UsuariosController');

    Route::post('ajax/order', 'Painel\AjaxController@order');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

laravel/app/models/Mostra.php
<?php

class Mostra extends Eloquent
{

    protected $table = 'mostras';

    protected $hidden = [];

    protected $fillable = ['titulo', 'capa'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC');
    }

    public function imagens()
    {
        return $this->hasMany('MostraImagem', 'mostras_id')->orderBy('ordem', 'ASC');
    }

}

laravel/app/controllers/MostrasController.php
<?php

use \Mostra;

class MostrasController extends BaseController {

    public function index()
    {
        $mostras = Mostra::with('imagens')->ordenados()->get();
        return $this->view('frontend.mostras', compact('mostras'));
    }

}

laravel/app/controllers/painel/AjaxController.php
<?php

namespace Painel;

use \Request, \Input, \DB, \Controller;

class AjaxController extends Controller {

    function order()
    {

        if (!Request::ajax()) return false;

        $menu   = Input::get('data');
        $tabela = Input::get('tabela');

        for ($i = 0; $i < count($menu); $i++) {
            DB::table($tabela)->where('id', $menu[$i])->update(array('ordem' => $i));
        }

        return json_encode($menu);

    }

}

laravel/app/controllers/painel/BannersController.php
<?php

namespace Painel;

use \Banner, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class BannersController extends BasePainelController {

    private $validation_rules = [
        'imagem' => 'required|image'
    ];

    private $image_config = [
        'width'  => 3000,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/banners/'
    ];

    public function index()
    {
        $banners = Banner::ordenados()->get();

        return $this->view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return $this->view('painel.banners.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['imagem'] = CropImage::make('imagem', $this->image_config);
            Banner::create($input);
            Session::flash('sucesso', 'Banner criado com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar banner.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $banner = Banner::findOrFail($id);

        return $this->view('painel.banners.edit', compact('banner'));
    }

    public function update($id)
    {
        $banner = Banner::findOrFail($id);
        $input  = Input::all();

        $this->validation_rules['imagem'] = 'image';
        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            } else {
                unset($input['imagem']);
            }

            $banner->update($input);
            Session::flash('sucesso', 'Banner alterado com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar banner.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            banner::destroy($id);
            Session::flash('sucesso', 'Banner removido com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover banner.']);

        }
    }

}

laravel/app/controllers/painel/BasePainelController.php
<?php

namespace Painel;

use \View, \ContatoRecebido;

class BasePainelController extends \Controller {

    protected $layout = 'painel.common.template';

    protected function setupLayout()
    {
        if ( ! is_null($this->layout))
        {
            $recebidos_count = ContatoRecebido::naoLidos()->count();
            View::share(compact('recebidos_count'));
            $this->layout = View::make($this->layout);
        }
    }

    protected function view($path, array $data = [])
    {
        $this->layout->content = View::make($path, $data);
    }

}

laravel/app/controllers/painel/ContatoController.php
<?php

namespace Painel;

use \Contato, \Input, \Session, \Redirect, \Validator;

class ContatoController extends BasePainelController {

    private $validation_rules = [
        'email' => 'required|email'
    ];

    public function index()
    {
    	$contato = Contato::first();

        return $this->view('painel.contato.index', compact('contato'));
    }

    public function update($id)
    {
        $contato = Contato::findOrFail($id);
        $input   = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $contato->update($input);
            Session::flash('sucesso', 'Informações de contato alteradas com sucesso.');

            return Redirect::route('painel.contato.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar informações de contato.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/ContatosRecebidosController.php
<?php

namespace Painel;

use \ContatoRecebido, \Session, \Redirect;

class ContatosRecebidosController extends BasePainelController {

    public function index()
    {
        $contatos_recebidos = ContatoRecebido::all();

        return $this->view('painel.contatosrecebidos.index', compact('contatos_recebidos'));
    }

    public function show($id)
    {
        $contato = ContatoRecebido::findOrFail($id);
        $contato->update(['lido' => 'true']);

        return $this->view('painel.contatosrecebidos.show', compact('contato'));
    }

    public function destroy($id)
    {
        try {

            ContatoRecebido::destroy($id);
            Session::flash('sucesso', 'Mensagem removida com sucesso.');

            return Redirect::route('painel.contato.recebidos.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover mensagem.']);

        }
    }

}

laravel/app/controllers/painel/HomeController.php
<?php

namespace Painel;

use \View, \Input, \Auth, \Session, \Redirect;

class HomeController extends BasePainelController {

    public function index()
    {
        return $this->view('painel.home');
    }

    public function login()
    {
        return $this->view('painel.login');
    }

    public function attempt()
    {
        $authvars = array(
            'username' => Input::get('username'),
            'password' => Input::get('password')
        );

        $lembrar = (Input::get('lembrar') == 'true') ? true : false;

        if (Auth::attempt($authvars, $lembrar)) {
            return Redirect::route('painel.home');
        } else {
            Session::flash('login_errors', true);
            return Redirect::route('painel.login')->withInput(Input::except('password'));
        }
    }

    public function logout()
    {
        Auth::logout();
        return Redirect::route('home');
    }

}

laravel/app/controllers/painel/ImprensaController.php
<?php

namespace Painel;

use \Imprensa, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class ImprensaController extends BasePainelController {

    private $validation_rules = [
        'titulo' => 'required',
        'capa'   => 'image',
        'pdf'    => 'mimes:pdf'
    ];

    private $image_config = [
        'width'  => 200,
        'height' => 200,
        'bg'     => '#E6E6E6',
        'path'   => 'assets/img/imprensa/capa/'
    ];

    public function index()
    {
        $imprensa = Imprensa::ordenados()->get();

        return $this->view('painel.imprensa.index', compact('imprensa'));
    }

    public function create()
    {
        return $this->view('painel.imprensa.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('capa')) {
                $input['capa'] = CropImage::make('capa', $this->image_config);
            } else {
                unset($input['capa']);
            }

            if (Input::has('video_codigo')) {
                $input['video_capa'] = \Tools::videoThumb($input['video_tipo'], $input['video_codigo']);
            }

            if (Input::hasFile('pdf')) {
                $input['pdf'] = $this->uploadPdf();
            }

            Imprensa::create($input);
            Session::flash('sucesso', 'Registro criado com sucesso.');

            return Redirect::route('painel.imprensa.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao criar registro: '.$e->getMessage()])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $imprensa = Imprensa::findOrFail($id);

        return $this->view('painel.imprensa.edit', compact('imprensa'));
    }

    public function update($id)
    {
        $imprensa = Imprensa::findOrFail($id);
        $input    = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('capa')) {
                $input['capa'] = CropImage::make('capa', $this->image_config);
            } else {
                unset($input['capa']);
            }

            if (Input::has('video_codigo') && $input['video_codigo'] != $imprensa->video_codigo || $input['video_tipo'] != $imprensa->video_tipo) {
                $input['video_capa'] = \Tools::videoThumb($input['video_tipo'], $input['video_codigo']);
            }

            if (Input::hasFile('pdf')) {
                $input['pdf'] = $this->uploadPdf();
            }

            $imprensa->update($input);
            Session::flash('sucesso', 'Registro alterado com sucesso.');

            return Redirect::route('painel.imprensa.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar registro: '.$e->getMessage()])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            Imprensa::destroy($id);
            Session::flash('sucesso', 'Registro removido com sucesso.');

            return Redirect::route('painel.imprensa.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover registro.']);

        }
    }

    public function deleteImage($id)
    {
        try {

            $imprensa = Imprensa::find($id);
            $imprensa->capa = null;
            $imprensa->save();

            Session::flash('sucesso', 'Imagem excluída com sucesso.');
            return Redirect::back();

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao excluir imagem.']);

        }
    }

    public function uploadPdf() {
        $file = Input::file('pdf');

        $path = 'assets/pdfs/';
        $name = preg_replace("([^\w\s\d\-_~,;:\[\]\(\).])", '', $file->getClientOriginalName());
        $name = date('YmdHis').'_'.$name;

        $file->move($path, $name);

        return $name;
    }

    public function deletePdf($id)
    {
        try {

            $imprensa = Imprensa::find($id);
            $imprensa->pdf = null;
            $imprensa->save();

            Session::flash('sucesso', 'Arquivo PDF excluído com sucesso.');
            return Redirect::back();

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao excluir PDF.']);

        }
    }
}

laravel/app/controllers/painel/ImprensaImagensController.php
<?php

namespace Painel;

use \Imprensa, \ImprensaImagem, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class ImprensaImagensController extends BasePainelController {

    private $validation_rules = [
        'imagem'   => 'required|image'
    ];

    private $image_config = [
        'width'  => 3000,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/imprensa/'
    ];

    public function index($imprensa_id)
    {
        $imprensa = Imprensa::find($imprensa_id);
        if(!$imprensa) return Redirect::route('painel.imprensa.index');

        $imagens = ImprensaImagem::imprensa($imprensa_id)->ordenados()->get();

        return $this->view('painel.imprensaimagens.index', compact('imprensa', 'imagens'));
    }

    public function create($imprensa_id)
    {
        $imprensa = Imprensa::find($imprensa_id);
        if(!$imprensa) return Redirect::route('painel.imprensa.index');

        return $this->view('painel.imprensaimagens.create', compact('imprensa'));
    }

    public function store($imprensa_id)
    {
        $input = Input::all();
        $input['imprensa_id'] = $imprensa_id;

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['imagem'] = CropImage::make('imagem', $this->image_config);
            $imagem = ImprensaImagem::create($input);

            $imagem->largura = getimagesize(asset('assets/img/imprensa/'.rawurlencode($input['imagem'])))[0];
            $imagem->altura = getimagesize(asset('assets/img/imprensa/'.rawurlencode($input['imagem'])))[1];
            $imagem->save();

            Session::flash('sucesso', 'Imagem inserida com sucesso.');

            return Redirect::route('painel.imprensa.imagens.index', $input['imprensa_id']);

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao inserir imagem.'])
                ->withInput();

        }
    }

    public function destroy($imprensa_id, $imagem_id)
    {
        try {

            ImprensaImagem::destroy($imagem_id);
            Session::flash('sucesso', 'Imagem removida com sucesso.');

            return Redirect::route('painel.imprensa.imagens.index', $imprensa_id);

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover imagem.']);

        }
    }

}

laravel/app/views/painel/mostras/_form.blade.php
@if($errors->any())
    @foreach($errors->all() as $error)
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ $error }}
    </div>
    @endforeach
@endif

@if(Session::has('sucesso'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ Session::get('sucesso') }}
    </div>
@endif

<div class="form-group">
    {{ Form::label('titulo', 'Título') }}
    {{ Form::text('titulo', null, ['class' => 'form-control']) }}
</div>

<div class="well form-group">
    {{ Form::label('capa', 'Imagem de capa') }}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/mostras/capa/'.$mostra->capa) }}" style="display:block; margin-bottom: 10px; max-width:300px;height:auto;">
@endif
    {{ Form::file('capa', ['class' => 'form-control']) }}
</div>

{{ Form::submit($submitText, ['class' => 'btn btn-success']) }}

<a href="{{ route('painel.mostras.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/app/views/painel/mostras/create.blade.php
@section('content')

    <legend>
        <h2>Adicionar Mostra</h2>
    </legend>

    {{ Form::open(['route' => 'painel.mostras.store', 'files' => true]) }}

        @include('painel.mostras._form', ['submitText' => 'Inserir'])

    {{ Form::close() }}

@stop

laravel/app/views/painel/mostras/edit.blade.php
@section('content')

    <legend>
        <h2>Editar Mostra</h2>
    </legend>

    {{ Form::model($mostra, [
        'route' => ['painel.mostras.update', $mostra->id],
        'method' => 'patch', 'files' => true])
    }}

        @include('painel.mostras._form', ['submitText' => 'Alterar'])

    {{ Form::close() }}

@stop

laravel/app/views/painel/mostras/index.blade.php
@section('content')

    @if($errors->any())
        @foreach($errors->all() as $error)
        <div class="alert alert-block alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ $error }}
        </div>
        @endforeach
    @endif

    @if(Session::has('sucesso'))
       <div class="alert alert-block alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ Session::get('sucesso') }}
        </div>
    @endif

    <legend>
        <h2>
            Mostras
            <a href="{{ route('painel.mostras.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Mostra</a>
        </h2>
    </legend>

    @if(count($mostras))
    <table class="table table-striped table-bordered table-hover table-sortable" data-tabela="mostras">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Capa</th>
                <th>Título</th>
                <th>Imagens</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($mostras as $mostra)

            <tr class="tr-row" id="id_{{ $mostra->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td><img src="{{ url('assets/img/mostras/capa/'.$mostra->capa) }}" alt="" style="width:100%;max-width:100px;height:auto;"></td>
                <td>{{ $mostra->titulo }}</td>
                <td><a href="{{ route('painel.mostras.imagens.index', $mostra->id) }}" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-picture" style="margin-right:10px;"></span>Gerenciar
                </a></td>
                <td class="crud-actions">
                    {{ Form::open(array('route' => array('painel.mostras.destroy', $mostra->id), 'method' => 'delete')) }}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.mostras.edit', $mostra->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {{ Form::close() }}
                </td>
            </tr>

        @endforeach
        </tbody>
    </table>
    @else
        <div class="alert alert-warning" role="alert">Nenhuma mostra cadastrada.</div>
    @endif

@stop